name: CI-Simple

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ]

jobs:

  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    - name: Set up Maven cache 1
      id: cache-maven1
      uses: actions/cache@v4
      with:
        path: |
          ~/.m2/repository
          target
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-   
    - name: Set up Maven cache 2
      id: cache-maven2    
      uses: actions/cache@v4
      with:
        path: |
          ~/.m2/repository
          target
        key: ${{ runner.os }}-maven-
        restore-keys: |
          ${{ runner.os }}-maven-
    - name: Check if Maven cache was hit
      if: steps.cache-maven2.outputs.cache-hit != 'true'
      run: echo "Cache 2 miss for Maven dependencies"
    - name: Set up Node.js cache
      uses: actions/cache@v4
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-          
    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'adopt'
        cache: maven
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '14'        
    - name: Build with Maven
      run: mvn --batch-mode --update-snapshots verify
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: package
        path: target/*.jar   
    - name: Install Node.js dependencies
      run: npm install        
