name: CI-With-Caching

on: workflow_dispatch

jobs:

  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'adopt'
        cache: maven
    - name: Run My Shell Action
      id: myaction
      uses: fuyibenchung/my-github-action-shell@5.0
      with:
          name: "Mary Jane"
    - name: Set up Maven cache 2
      id: cache-maven2    
      uses: actions/cache@v4
      with:
        path: |
          ~/.m2/repository
          target
        key: ${{ runner.os }}-maven-
        restore-keys: |
          ${{ runner.os }}-maven-
    - name: Check if Maven cache was hit
      if: steps.cache-maven2.outputs.cache-hit != 'true'
      run: echo "Cache 2 miss for Maven dependencies, value:${{steps.cache-maven2.outputs.cache-hit}}"            
    - name: Use output from My Shell Action
      run: "echo 'The greeting message is: ${{ steps.myaction.outputs.greeting }}'"         
    - name: Build with Maven
      run: mvn --batch-mode --update-snapshots verify

    
