name: CI-With-Dependency

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ]

jobs:

  build-library:
    name: Build Simple Library
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Simple Library code
        uses: actions/checkout@v3
        with:
          repository: fuyibenchung/simple-library  # Replace with your `simple-library` repository
          path: simple-library  # Checkout into the `simple-library` directory

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: maven

      - name: Build Simple Library
        run: |
          cd simple-library
          mvn clean install

  build-webapp:
    name: Build Java Web App
    runs-on: ubuntu-latest
    needs: build-library  # Depend on the successful completion of the library build
    
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'adopt'
        cache: maven
    - name: Build Java Web App
      run: mvn --batch-mode --update-snapshots verify
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: package
        path: target/*.jar
    - name: Greet someone
      uses: fuyibenchung/my-github-action@3.0
      with:
        name: 'John Doe'  
    - name: Run My Shell Action
      id: myaction
      uses: fuyibenchung/my-github-action-shell@1.0
      with:
          name: "Mary Jane"
    - name: Use output from My Shell Action
      run: "echo 'The greeting message is: ${{ steps.myaction.outputs.greeting }}'"           
